tdbFolder: "../tdb/"
datamodelFile: "../resources/ontologies/datamodel.owl"
interoperabilitymodelFile: "../resources/ontologies/interoperabilitymodel.owl"
functionalmodelFile: "../resources/ontologies/functionalmodel.owl"
uploadFolder: "../upload/"
exiftoolWindowsPath: "C:\\WINDOWS\\exiftool.exe"
exiftoolUnixPath: "/usr/local/bin/exiftool"
