tdbFolder: "../tdb"
datamodelFile: "../resources/ontologies/datamodel.owl"
interoperabilitymodelFile: "../resources/ontologies/interoperabilitymodel.owl"
functionalmodelFile: "../resources/ontologies/functionalmodel.owl"
